version: "2"

services:
  app:
    container_name: cachecontainer
    restart: always
    build: ./
    ports:
      - "8084:8084"
    volumes:
      - .:/app
    links:
      - redis
  redis:
    container_name: rediscontainer
    image: redis
    ports:
      - "6379:6379"
